import { Injectable } from '@nestjs/common';

/**
 * The boundary between the app and wherever attachment bytes actually live. Phase 4 keeps the
 * metadata (`file_records`/`file_versions`) in Postgres and puts the bytes behind this port so
 * the storage backend is a swap, not a rewrite: the {@link InMemoryStorageAdapter} below is the
 * current binding, and a MinIO/S3 adapter (private bucket, server-generated keys) drops in later
 * without touching the upload/download use cases.
 *
 * Keys are generated by the caller (the file-version repository), never by the client, and
 * `put` refuses to overwrite — a version's bytes are written once and never mutated, matching the
 * immutability the `file_versions` table enforces on its metadata.
 */
@Injectable()
export abstract class StoragePort {
  /** Stores bytes under a fresh key. Throws if the key already holds an object (no overwrite). */
  abstract put(key: string, bytes: Uint8Array): Promise<void>;
  /** Returns the stored bytes, or `null` if the key is unknown. */
  abstract get(key: string): Promise<Uint8Array | null>;
}

/**
 * In-memory stand-in for the private object bucket (the MinIO quarantine prefix). Good enough
 * for the app and its tests until the real adapter lands; the bytes do not survive a restart,
 * which is exactly why the metadata that must survive lives in Postgres instead.
 */
@Injectable()
export class InMemoryStorageAdapter extends StoragePort {
  readonly #objects = new Map<string, Uint8Array>();

  put(key: string, bytes: Uint8Array): Promise<void> {
    if (this.#objects.has(key))
      return Promise.reject(new Error(`Refusing to overwrite existing object at ${key}`));
    this.#objects.set(key, bytes);
    return Promise.resolve();
  }

  get(key: string): Promise<Uint8Array | null> {
    return Promise.resolve(this.#objects.get(key) ?? null);
  }
}
